from math import sin, radians, sqrt, cos
x = int(input("Введите число"))
a = int(input("Введите число"))
n = int(input("Введите число"))
y = int(input("Введите число"))
B = int(input("Введите число"))

aa = (f"а) 2 * x = {2 * x}")
b = (f"б) sin x = {round(sin(radians(x))), 2}")
v = (f"в) a^2 = {a * a}")
g = (f"г) √x = {sqrt(x)}")
d = (f"д) |n| = {abs(n)}")
e = (f"е) 5cos y = {round(5*cos(radians(a)))}")
zh =(f"ж) -7,5a^2 = {-7.5 * a ** 2}")
z = (f"з) 3√x = {round(3*sqrt(x),2)}")
i =(f"и) sin a*cosB + cos a * sin B= \{round(sin(radians(a))) * (cos(radians(B)))+ (cos(radians(a)))*(sin(radians(B)))}")
k =(f"к)a√2b = {round(3*sqrt(2*B),2)}")
l = (f"л) 3sin 2a * cos 3B= {3*(sin(radians(2*a)))*(cos(radians(3*B)))}")
m = (f"м) -5√x-√y= {-5 * sqrt(x +sqrt(y))}")

print(f"{aa}")
print(f"{b}")
print(f"{v}")
print(f"{g}")
print(f"{d}")
print(f"{e}")
print(f"{zh}")
print(f"{z}")
print(f"{i}")
print(f"{k}")
print(f"{l}")
print(f"{m}")