number1 = int(input("введите число"))
number2 = int(input("введите число"))
number3 = int(input("введите число"))
number4 = int(input("введите число"))
print(number1)
print(number2)
print(number3)
print(number4)