number1 = int(input("введите число"))
number2 = int(input("введите число"))
number3 = int(input("введите число"))
number4 = int(input("введите число"))
print(number1,"",number2,"",number3,"",number4)